# build:
#   stage: build
#   script:
#     - docker build -t test_container .
#     - docker run -v .:/app test_container
before_script:
  - docker info
test:
  script:
    - docker build -t ci_test .
    - docker run --rm -v ${PWD}/:/app  ci_test pytest tests/test_lighting_sm.py