# build:
#   stage: build
#   script:
#     - docker build -t test_container .
#     - docker run -v .:/app test_container
before_script:
  - docker info
test-component:
  script:
    - docker build -t component_test -f Dockerfile.component .
    - docker-compose up component-test-ci
# test:
#   script:
#     - docker build -t ci_test -f Dockerfile.ci-test .
#     - docker run --rm ci_test