# build:
#   stage: build
#   script:
#     - docker build -t test_container .
#     - docker run -v .:/app test_container
before_script:
  - docker info
test-component:
  script:
    - docker build -t component_test -f Dockerfile.component .
    - docker run --rm -v ./custom_components/lightingsm.py:/usr/src/app/homeassistant/components/lightingsm.py:ro       -v ./tests/test_lightingsm.py:/usr/src/app/tests/components/test_lightingsm.py:ro       -v ./pytest.ini:/usr/src/app/pytest.ini:ro component_test ptw -- -sv
# test:
#   script:
#     - docker build -t ci_test -f Dockerfile.ci-test .
#     - docker run --rm ci_test