
version: '3.3'
services:
  test:
    build: .
    container_name: testing
    volumes:
      - .:/app
    # command: [ "pytest-watch", "--ext=.py,.yaml", "--","-s","--tb=line" ]
  hass-test:
    build: 
      context: .
      dockerfile: Dockerfile.component 
    container_name: component-test
    # command: [ "ptw","--","-sv" ]
    restart: unless-stopped
    # networks:
    #     - "local"
    #     - "public"
    # links:
    #     - db
    # external_links:
    #     - mqtt
    # ports:
    #     - 8111:8123
    # volumes:
        # - G:\Repos\hass-dev:/config
        # - ${$PWD}/tests/test_lightingsm.py:/usr/src/app/tests/components/test_lightingsm.py
        # - ${$PWD}/pytest.ini:/usr/src/app/pytest.ini
        # - ${PWD}:/usr/src/app

