
version: '3.3'
services:
  test:
    build: .
    container_name: testing
    volumes:
      - .:/app
    # command: [ "pytest-watch", "--ext=.py,.yaml", "--","-s","--tb=line" ]
  hass-test:
    build: 
      context: .
      dockerfile: Dockerfile.component 
    container_name: component-test
    command: [ "ptw","--","-sv" ]

    volumes:
        # - G:\Repos\hass-dev:/config
      - ./custom_components/lightingsm.py:/usr/src/app/components/lightingsm.py
      - ./tests/test_lightingsm.py:/usr/src/app/tests/components/test_lightingsm.py
      - ./pytest.ini:/usr/src/app/pytest.ini
        # - ${PWD}:/usr/src/app
  component-test-ci:
    build: 
      context: .
      dockerfile: Dockerfile.component 
    container_name: component-test-ci
    command: [ "pytest" ]

    volumes:
        # - G:\Repos\hass-dev:/config
      - ./custom_components/lightingsm.py:/usr/src/app/components/lightingsm.py
      - ./tests/test_lightingsm.py:/usr/src/app/tests/components/test_lightingsm.py
      - ./pytest.ini:/usr/src/app/pytest.ini
        # - ${PWD}:/usr/src/app

