---
control:
  description: Manual control of an entity_controller device from an external automation or service call.
  fields:
    entity_id:
      description: Name(s) of the entities to control
      example: 'entity_controller.hallway_motion'
    command:
      description: Control action to perform on the entity controller.
      example: 'enable'
